spring:
  datasource:
    url: jdbc:mysql://192.168.209.101:3306/mybatis #?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: jiaxu123
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

#    druid:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      initialSize: 60
#      minIdle: 60
#      maxActive: 60
#      maxWait: 10000
#      minEvictableIdleTimeMillis: 300000
#      timeBetweenEvictionRunsMillis: 60000
#      validationQuery: SELECT 1
#      testOnBorrow: false
#      testOnReturn: false
#      testWhileIdle: true
#      filters: config,stat
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.jiaxuch.excel.model.*
  configuration:
    map-underscore-to-camel-case: true
#logging:
#  level: debug
#  file:
#    path: logs/poi.log

